name: Kani CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  kani:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        feature-set:
          - ""
          - '--features "allow-unsafe"'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Kani ${{ matrix.feature-set }}
        uses: model-checking/kani-github-action@v1
        with:
          args: '--tests ${{ matrix.feature-set }}'
