name: Kani CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  kani:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Kani
        uses: model-checking/kani-github-action@v1
        with:
          args: '--tests'
